// Language configuration
export const config = {
    languages: {
        en: {
            appTitle: "Time Series Analysis",
            importBtn: "Import Excel",
            descriptiveBtn: "Descriptive Statistics",
            regressionBtn: "Multiple Linear Regression",
            ardlBtn: "ARDL Analysis",
            welcomeTitle: "Welcome to Time Series Analysis Tool",
            welcomeDesc: "Import your Excel file to begin analyzing time series data",
            dropText: "Drag & drop your Excel file here or click to browse",
            timeColLabel: "Time Column:",
            valueColLabel: "Value Columns:",
            statsTitle: "Descriptive Statistics",
            regressionTitle: "Multiple Linear Regression",
            dependentVarLabel: "Dependent Variable:",
            independentVarsLabel: "Independent Variables:",
            runRegressionBtn: "Run Regression",
            runStatsBtn: "Calculate Statistics",
            statsVarsLabel: "Variables:",
            mean: "Mean",
            median: "Median",
            min: "Minimum",
            max: "Maximum",
            variance: "Variance",
            stdDev: "Standard Deviation",
            skewness: "Skewness",
            kurtosis: "Kurtosis",
            quartile1: "1st Quartile",
            quartile3: "3rd Quartile",
            iqr: "Interquartile Range",
            coefficients: "Coefficients",
            variable: "Variable",
            value: "Value",
            pValue: "p-value",
            rSquared: "R-squared",
            adjustedRSquared: "Adjusted R-squared",
            fStatistic: "F-statistic",
            pValueModel: "p-value (model)",
            actualVsPredicted: "Actual vs Predicted Values",
            actual: "Actual",
            predicted: "Predicted",
            residuals: "Residuals",
            standardError: "Standard Error",
            tStatistic: "t-statistic",
            intercept: "Intercept",
            showTableBtn: "Show Data Table",
            hideTableBtn: "Hide Data Table",
            toggleTableBtn: "Hide Data Table",
            transformationLabel: "Transformation:",
            differenceLabel: "Differencing:",
            timeSeriesModelLabel: "Time Series Model:",
            dummyYearColumnLabel: "Year Column for Dummies:",
            dummyYearsLabel: "Select Years for Dummies:",
            dummyQuartersLabel: "Include Quarters:",
            noQuarters: "No Quarters",
            noneOption: "None",
            logTransform: "Logarithm (ln)",
            squareTransform: "Square (x²)",
            sqrtTransform: "Square Root (√x)",
            inverseTransform: "Inverse (1/x)",
            cubeTransform: "Cube (x³)",
            boxcoxTransform: "Box-Cox",
            firstDiff: "First Difference",
            secondDiff: "Second Difference",
            seasonalDiff: "Seasonal (lag=12)",
            ar1Model: "AR(1)",
            ar2Model: "AR(2)",
            ma1Model: "MA(1)",
            ma2Model: "MA(2)",
            arma11Model: "ARMA(1,1)",
            significant: "Significant",
            notSignificant: "Not Significant",
            durbinWatson: "Durbin-Watson",
            fisherTest: "F-test",
            modelSignificant: "Model Significance",
            regressionEquation: "Regression Equation",
            ardlTitle: "ARDL Analysis",
            dependentLags: "Dependent Variable Lags:",
            independentLags: "Independent Variables Lags:",
            boundTestResult: "Bounds Test Result:",
            longRunRelationship: "Long-run Relationship:",
            longRunCoefficients: "Long-run Coefficients",
            shortRunCoefficients: "Short-run Coefficients",
            errorCorrection: "Error Correction Term:",
            ardlModel: "ARDL Model Specification:",
            diagnosticTests: "Diagnostic Tests",
            jarqueBera: "Jarque-Bera Normality Test",
            residualsNormal: "Residuals Normality",
            serialCorrelation: "Serial Correlation Test",
            heteroskedasticity: "Heteroskedasticity Test (White)",
            noSerialCorrelation: "No Serial Correlation",
            homoskedastic: "Homoskedastic",
            heteroskedastic: "Heteroskedastic",
            normal: "Normal",
            notNormal: "Not Normal",
            stdError: "Standard Error",
            coeffVar: "Coefficient of Variation",
            geometricMean: "Geometric Mean",
            harmonicMean: "Harmonic Mean",
            mode: "Mode",
            range: "Range",
            sum: "Sum",
            count: "Count",
            percentile: "Percentile",
            selectStats: "Select Statistics to Display",
            updateDisplay: "Update Display",
            basicStats: "Basic (Mean, Median, Min, Max)",
            dispersionStats: "Dispersion (Variance, StdDev, Range)",
            shapeStats: "Shape (Skewness, Kurtosis)",
            quartilesStats: "Quartiles",
            advancedStats: "Advanced (CV, SEM, Geometric Mean)",
            modeStats: "Mode",
            quantilesStats: "Deciles",
            countStats: "Count & Sum",
            normalityTests: "Normality Tests (Kolmogorov-Smirnov, Shapiro-Wilk)",
            advancedTsBtn: "Advanced Time Series",
            advancedTsTitle: "Advanced Time Series Analysis",
            varModel: "Vector Autoregression (VAR)",
            vecmModel: "Vector Error Correction Model (VECM)",
            johansenTest: "Johansen Cointegration Test",
            armaModel: "ARMA Model",
            runAdvTsAnalysis: "Run Analysis",
            advVariablesLabel: "Variables:",
            advTransformLabel: "Transformation:",
            advDiffLabel: "Differencing:",
            modelType: "Model Type:",
            lagOrder: "Lag Order:",
            deterministic: "Deterministic Terms:",
            cointRank: "Cointegration Rank:",
            arOrder: "AR Order (p):",
            maOrder: "MA Order (q):",
            stationarityBtn: "Stationarity Analysis",
            stationarityTitle: "Time Series Stationarity Analysis",
            stationarityVarsLabel: "Variables:",
            stationarityTransformLabel: "Transformation:",
            stationarityDiffLabel: "Differencing:",
            stationarityTestLabel: "Test Type:",
            stationarityLagLabel: "Max Lag:",
            runStationarityText: "Run Analysis",
            adfTest: "Augmented Dickey-Fuller Test",
            ppTest: "Phillips-Perron Test",
            kpssTest: "KPSS Test",
            stationaryResult: "Stationary",
            nonStationaryResult: "Non-Stationary",
            testStatistic: "Test Statistic",
            criticalValues: "Critical Values",
            armaFit: "ARMA Model Fit",
            armaPLabel: "AR Order (p):",
            armaQLabel: "MA Order (q):",
            originalSeries: "Original Series",
            transformedSeries: "Transformed Series",
            acfTitle: "Autocorrelation Function",
            pacfTitle: "Partial Autocorrelation Function",
            panelBtn: "Panel Data Analysis",
            panelTitle: "Panel Data Analysis",
            panelEntityColLabel: "Entity ID Column:",
            panelTimeColLabel: "Time Period Column:",
            panelModelTypeLabel: "Model Type:",
            panelEffectsLabel: "Effects:",
            panelRobustLabel: "Robust Standard Errors:",
            panelClusterLabel: "Cluster by Entity:",
            runPanelText: "Run Panel Analysis",
            chartTypes: {
                none: "No Chart",
                histogram: "Histogram",
                boxplot: "Box Plot",
                violin: "Violin Plot",
                density: "Density Plot",
                correlogram: "Correlogram",
                scatter: "Scatter Plot",
                bar: "Bar Plot",
                line: "Line Plot",
                qqplot: "QQ Plot",
                ppplot: "PP Plot",
                logit: "Logit Plot",
                probit: "Probit Plot"
            }
        },
        ar: {
            appTitle: "تحليل السلاسل الزمنية",
            importBtn: "استيراد ملف إكسل",
            descriptiveBtn: "الإحصاء الوصفي",
            regressionBtn: "الانحدار الخطي المتعدد",
            ardlBtn: "تحليل ARDL",
            welcomeTitle: "مرحباً بك في أداة تحليل السلاسل الزمنية",
            welcomeDesc: "قم باستيراد ملف إكسل للبدء في تحليل بيانات السلاسل الزمنية",
            dropText: "اسحب وأفلت ملف الإكسل هنا أو انقر للتصفح",
            timeColLabel: "عمود الوقت:",
            valueColLabel: "أعمدة القيم:",
            statsTitle: "الإحصاء الوصفي",
            regressionTitle: "الانحدار الخطي المتعدد",
            dependentVarLabel: "المتغير التابع:",
            independentVarsLabel: "المتغيرات المستقلة:",
            runRegressionBtn: "تشغيل الانحدار",
            runStatsBtn: "حساب الإحصاءات",
            statsVarsLabel: "المتغيرات:",
            mean: "المتوسط",
            median: "الوسيط",
            min: "الحد الأدنى",
            max: "الحد الأقصى",
            variance: "التباين",
            stdDev: "الانحراف المعياري",
            skewness: "الالتواء",
            kurtosis: "التفرطح",
            quartile1: "الربيع الأول",
            quartile3: "الربيع الثالث",
            iqr: "المدى الربيعي",
            coefficients: "المعاملات",
            variable: "المتغير",
            value: "القيمة",
            pValue: "القيمة الاحتمالية",
            rSquared: "معامل التحديد R²",
            adjustedRSquared: "معامل التحديد المعدل",
            fStatistic: "إحصائية F",
            pValueModel: "القيمة الاحتمالية (النموذج)",
            actualVsPredicted: "القيم الفعلية مقابل القيم المتوقعة",
            actual: "الفعلية",
            predicted: "المتوقعة",
            residuals: "البواقي",
            standardError: "الخطأ المعياري",
            tStatistic: "إحصائية t",
            intercept: "الثابت",
            showTableBtn: "إظهار جدول البيانات",
            hideTableBtn: "إخفاء جدول البيانات",
            toggleTableBtn: "إخفاء جدول البيانات",
            transformationLabel: "التحويل:",
            differenceLabel: "الفروقات:",
            timeSeriesModelLabel: "نموذج السلسلة الزمنية:",
            dummyYearColumnLabel: "عمود السنوات للمتغيرات الصورية:",
            dummyYearsLabel: "اختر السنوات للمتغيرات الصورية:",
            dummyQuartersLabel: "تضمين الأرباع السنوية:",
            noQuarters: "بدون أرباع",
            noneOption: "بدون",
            logTransform: "لوغاريتم (ln)",
            squareTransform: "تربيع (x²)",
            sqrtTransform: "جذر تربيعي (√x)",
            inverseTransform: "مقلوب (1/x)",
            cubeTransform: "مكعب (x³)",
            boxcoxTransform: "بوكس-كوكس",
            firstDiff: "الفرق الأول",
            secondDiff: "الفرق الثاني",
            seasonalDiff: "موسمي (فجوة=12)",
            ar1Model: "AR(1)",
            ar2Model: "AR(2)",
            ma1Model: "MA(1)",
            ma2Model: "MA(2)",
            arma11Model: "ARMA(1,1)",
            significant: "معنوي",
            notSignificant: "غير معنوي",
            durbinWatson: "داربن واتسون",
            fisherTest: "اختبار فيشر",
            modelSignificant: "معنوية النموذج",
            regressionEquation: "معادلة الانحدار",
            ardlTitle: "تحليل ARDL",
            dependentLags: "فترات الإبطاء للمتغير التابع:",
            independentLags: "فترات الإبطاء للمتغيرات المستقلة:",
            boundTestResult: "نتيجة اختبار الحدود:",
            longRunRelationship: "العلاقة طويلة الأجل:",
            longRunCoefficients: "معاملات العلاقة طويلة الأجل",
            shortRunCoefficients: "معاملات العلاقة قصيرة الأجل",
            errorCorrection: "معامل تصحيح الخطأ:",
            ardlModel: "مواصفات نموذج ARDL:",
            diagnosticTests: "اختبارات تشخيص النموذج",
            jarqueBera: "اختبار جارك بيرا للتوزيع الطبيعي",
            residualsNormal: "طبيعية البواقي",
            serialCorrelation: "اختبار الارتباط التسلسلي",
            heteroskedasticity: "اختبار عدم تجانس التباين (وايت)",
            noSerialCorrelation: "لا يوجد ارتباط تسلسلي",
            homoskedastic: "تجانس التباين",
            heteroskedastic: "عدم تجانس التباين",
            normal: "طبيعي",
            notNormal: "غير طبيعي",
            stdError: "الخطأ المعياري",
            coeffVar: "معامل الاختلاف",
            geometricMean: "المتوسط الهندسي",
            harmonicMean: "المتوسط التوافقي",
            mode: "المنوال",
            range: "المدى",
            sum: "المجموع",
            count: "العدد",
            percentile: "المئين",
            selectStats: "اختر الإحصاءات للعرض",
            updateDisplay: "تحديث العرض",
            basicStats: "أساسية (المتوسط، الوسيط، الحد الأدنى، الحد الأقصى)",
            dispersionStats: "التشتت (التباين، الانحراف المعياري، المدى)",
            shapeStats: "الشكل (الالتواء، التفرطح)",
            quartilesStats: "الربيعات",
            advancedStats: "متقدمة (معامل الاختلاف، الخطأ المعياري، المتوسط الهندسي)",
            modeStats: "المنوال",
            quantilesStats: "العشيرات",
            countStats: "العدد والمجموع",
            normalityTests: "اختبارات التوزيع الطبيعي (كولموجوروف-سميرنوف، شابيرو-ويلك)",
            advancedTsBtn: "تحليل السلاسل الزمنية المتقدم",
            advancedTsTitle: "تحليل السلاسل الزمنية المتقدم",
            varModel: "نموذج متجه الانحدار الذاتي (VAR)",
            vecmModel: "نموذج تصحيح الخطأ المتجهي (VECM)",
            johansenTest: "اختبار جوهانسن للتكامل المشترك",
            armaModel: "نموذج ARMA",
            runAdvTsAnalysis: "تشغيل التحليل",
            advVariablesLabel: "المتغيرات:",
            advTransformLabel: "التحويل:",
            advDiffLabel: "الفروقات:",
            modelType: "نوع النموذج:",
            lagOrder: "عدد فترات الإبطاء:",
            deterministic: "الحدود الثابتة:",
            cointRank: "رتبة التكامل المشترك:",
            arOrder: "رتبة AR (p):",
            maOrder: "رتبة MA (q):",
            stationarityBtn: "تحليل استقرارية السلاسل",
            stationarityTitle: "تحليل استقرارية السلاسل الزمنية",
            stationarityVarsLabel: "المتغيرات:",
            stationarityTransformLabel: "التحويل:",
            stationarityDiffLabel: "الفروقات:",
            stationarityTestLabel: "نوع الاختبار:",
            stationarityLagLabel: "الإبطاء الأقصى:",
            runStationarityText: "تشغيل التحليل",
            adfTest: "اختبار ديكي-فولر الموسع",
            ppTest: "اختبار فيليبس-بيرون",
            kpssTest: "اختبار KPSS",
            stationaryResult: "مستقرة",
            nonStationaryResult: "غير مستقرة",
            testStatistic: "إحصائية الاختبار",
            criticalValues: "القيم الحرجة",
            armaFit: "نموذج ARMA",
            armaPLabel: "رتبة AR (p):",
            armaQLabel: "رتبة MA (q):",
            originalSeries: "السلسلة الأصلية",
            transformedSeries: "السلسلة المحولة",
            acfTitle: "دالة الارتباط الذاتي",
            pacfTitle: "دالة الارتباط الذاتي الجزئي",
            panelBtn: "تحليل بيانات البانل",
            panelTitle: "تحليل بيانات البانل",
            panelEntityColLabel: "عمود هوية الكيان:",
            panelTimeColLabel: "عمود الفترة الزمنية:",
            panelModelTypeLabel: "نوع النموذج:",
            panelEffectsLabel: "التأثيرات:",
            panelRobustLabel: "الأخطاء المعيارية القوية:",
            panelClusterLabel: "تجميع حسب الكيان:",
            runPanelText: "تشغيل تحليل البانل",
            chartTypes: {
                none: "بدون رسم بياني",
                histogram: "مدرج تكراري",
                boxplot: "رسم صندوقي",
                violin: "رسم كمان",
                density: "رسم الكثافة",
                correlogram: "مصفوفة الارتباط",
                scatter: "رسم الانتشار",
                bar: "رسم شريطي",
                line: "رسم خطي",
                qqplot: "رسم Q-Q",
                ppplot: "رسم P-P",
                logit: "رسم لوجيت",
                probit: "رسم بروبيت"
            }
        }
    },
    defaultLanguage: "en"
};